FROM python:3.9-slim

# Устанавливаем системные зависимости (dlib требует cmake, make, gcc и т.д.)
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "app.py"]
