version: '3.8'

services:
  postgres:
    container_name: zeep-postgres
    image: postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - ./.env

  pgadmin:
    container_name: zeep-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    restart: unless-stopped
    env_file:
      - ./.env

  redis:
    container_name: zeep-redis
    image: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    restart: unless-stopped
    env_file:
      - ./.env

  redisinsight:
    container_name: zeep-redisinsight
    image: redis/redisinsight:latest
    depends_on:
      - redis
    ports:
      - '8001:8001'
    environment:
      REDIS_HOST: zeep-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped
    env_file:
      - ./.env

volumes:
  postgres-data:
