name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./fontend
        run: npm install

      - name: Run ESLint
        working-directory: ./fontend
        run: npm run lint

      - name: Run Prettier
        working-directory: ./fontend
        run: npm run format

      - name: Run tests
        working-directory: ./fontend
        run: npm test:unit

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install golangci-lint
        working-directory: ./backend
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Run golangci-lint
        working-directory: ./backend
        run: golangci-lint run

      - name: Run tests
        working-directory: ./backend
        run: go test ./...
